import PDFDocument from 'pdfkit';

/**
 * Server-side PDF generation for maintenance bills, payment receipts and
 * expense vouchers. Documents are branded from the society's identity
 * (name / address / GSTIN) and built with PDFKit's standard fonts.
 *
 * NOTE: the rupee glyph (₹) is not in the WinAnsi standard fonts, so amounts
 * are rendered as "Rs." to stay portable without embedding a custom font.
 */

export interface SocietyIdentity {
  name: string;
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  gstin?: string | null;
}

export interface BillData {
  invoiceNumber: string;
  unitNumber: string;
  residentName?: string | null;
  billingPeriod: string;
  dueDate: string;
  status: string;
  lineItems: { description: string; quantity: number; unitPrice: number; amount: number }[];
  taxAmount: number;
  lateFee: number;
  totalAmount: number;
  amountPaid: number;
}

export interface ReceiptData {
  invoiceNumber: string;
  unitNumber: string;
  receivedFrom?: string | null;
  billingPeriod: string;
  paidOn: string;
  method: string;
  reference?: string | null;
  amount: number;
}

export interface VoucherData {
  voucherNumber: string;
  category: string;
  payee?: string | null;
  date: string;
  title: string;
  amount: number;
}

type Doc = PDFKit.PDFDocument;

const GREEN = '#1f6f4d';
const INK = '#14201c';
const MUTED = '#6e6e6e';

const rs = (n: number) => `Rs. ${Math.round(n).toLocaleString('en-IN')}`;
const addr = (s: SocietyIdentity) =>
  [s.addressLine1, s.addressLine2, `${s.city}, ${s.state} ${s.postalCode}`].filter(Boolean).join(', ');

/** Build a PDF in memory and resolve the complete byte buffer. */
function renderToBuffer(build: (doc: Doc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      build(doc);
      doc.end();
    } catch (err) {
      reject(err as Error);
    }
  });
}

/** Branded letterhead + a titled section line. */
function header(doc: Doc, society: SocietyIdentity, title: string): void {
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(16).text(society.name, 50, 50);
  doc.font('Helvetica').fontSize(9).fillColor(MUTED).text(addr(society), 50, 72);
  if (society.gstin) doc.text(`GSTIN: ${society.gstin}`, 50, 84);

  doc.moveTo(50, 100).lineTo(545, 100).strokeColor(GREEN).lineWidth(1.2).stroke();
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(13).text(title, 50, 112);
}

function footer(doc: Doc, society: SocietyIdentity): void {
  doc.font('Helvetica').fontSize(8).fillColor('#9a9a9a').text(`Generated by ${society.name} — Societify`, 50, 790, {
    width: 495,
    align: 'center',
  });
}

function kvRow(doc: Doc, y: number, k: string, v: string): number {
  doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(k, 50, y);
  doc.fillColor(INK).text(v, 300, y, { width: 245, align: 'right' });
  return y + 18;
}

function signatures(doc: Doc, y: number): void {
  doc.strokeColor('#bdbdbd').lineWidth(0.5);
  doc.moveTo(70, y).lineTo(230, y).stroke();
  doc.moveTo(330, y).lineTo(490, y).stroke();
  doc.font('Helvetica').fontSize(9).fillColor(MUTED);
  doc.text('Authorised signatory', 70, y + 6, { width: 160, align: 'center' });
  doc.text('Treasurer', 330, y + 6, { width: 160, align: 'center' });
}

export function buildBillPdf(society: SocietyIdentity, bill: BillData): Promise<Buffer> {
  return renderToBuffer((doc) => {
    header(doc, society, 'Maintenance Bill');
    let y = 145;
    y = kvRow(doc, y, 'Bill number', bill.invoiceNumber);
    y = kvRow(doc, y, 'Unit', bill.unitNumber);
    if (bill.residentName) y = kvRow(doc, y, 'Resident', bill.residentName);
    y = kvRow(doc, y, 'Billing period', bill.billingPeriod);
    y = kvRow(doc, y, 'Due date', bill.dueDate);
    y = kvRow(doc, y, 'Status', bill.status);

    y += 6;
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#dcdcdc').lineWidth(0.5).stroke();
    y += 12;

    // Line items
    doc.font('Helvetica-Bold').fontSize(10).fillColor(MUTED);
    doc.text('Description', 50, y);
    doc.text('Qty', 330, y, { width: 60, align: 'right' });
    doc.text('Amount', 430, y, { width: 115, align: 'right' });
    y += 16;
    doc.font('Helvetica').fontSize(10).fillColor(INK);
    for (const li of bill.lineItems) {
      doc.text(li.description, 50, y, { width: 270 });
      doc.text(String(li.quantity), 330, y, { width: 60, align: 'right' });
      doc.text(rs(li.amount), 430, y, { width: 115, align: 'right' });
      y += 16;
    }

    y += 4;
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#dcdcdc').lineWidth(0.5).stroke();
    y += 12;
    if (bill.taxAmount > 0) y = kvRow(doc, y, 'Tax', rs(bill.taxAmount));
    if (bill.lateFee > 0) y = kvRow(doc, y, 'Late fee', rs(bill.lateFee));

    doc.font('Helvetica-Bold').fontSize(13).fillColor(INK);
    doc.text('Total payable', 50, y + 4);
    doc.text(rs(bill.totalAmount), 330, y + 4, { width: 215, align: 'right' });
    if (bill.amountPaid > 0) {
      y += 22;
      doc.font('Helvetica').fontSize(10).fillColor(MUTED);
      doc.text('Paid', 50, y);
      doc.text(rs(bill.amountPaid), 330, y, { width: 215, align: 'right' });
    }

    signatures(doc, y + 70);
    footer(doc, society);
  });
}

export function buildReceiptPdf(society: SocietyIdentity, r: ReceiptData): Promise<Buffer> {
  return renderToBuffer((doc) => {
    header(doc, society, 'Payment Receipt');
    let y = 145;
    y = kvRow(doc, y, 'Receipt for', r.invoiceNumber);
    y = kvRow(doc, y, 'Unit', r.unitNumber);
    if (r.receivedFrom) y = kvRow(doc, y, 'Received from', r.receivedFrom);
    y = kvRow(doc, y, 'Billing period', r.billingPeriod);
    y = kvRow(doc, y, 'Payment date', r.paidOn);
    y = kvRow(doc, y, 'Mode', r.reference ? `${r.method} · ${r.reference}` : r.method);

    y += 6;
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#dcdcdc').lineWidth(0.5).stroke();
    y += 12;
    doc.font('Helvetica-Bold').fontSize(13).fillColor(INK);
    doc.text('Amount received', 50, y);
    doc.text(rs(r.amount), 330, y, { width: 215, align: 'right' });

    doc.font('Helvetica').fontSize(8).fillColor('#9a9a9a').text(
      'Received with thanks · system-generated, no signature required',
      50,
      y + 28,
    );
    footer(doc, society);
  });
}

export function buildVoucherPdf(society: SocietyIdentity, v: VoucherData): Promise<Buffer> {
  return renderToBuffer((doc) => {
    header(doc, society, 'Payment Voucher');
    let y = 145;
    y = kvRow(doc, y, 'Voucher number', v.voucherNumber);
    y = kvRow(doc, y, 'Category', v.category);
    if (v.payee) y = kvRow(doc, y, 'Paid to', v.payee);
    y = kvRow(doc, y, 'Date', v.date);

    y += 6;
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#dcdcdc').lineWidth(0.5).stroke();
    y += 12;
    doc.font('Helvetica').fontSize(11).fillColor(INK).text(v.title, 50, y, { width: 280 });
    doc.font('Helvetica-Bold').fontSize(13).text(rs(v.amount), 330, y, { width: 215, align: 'right' });

    signatures(doc, y + 70);
    footer(doc, society);
  });
}
